### ISSUE TITLE
Syntax error on Python 3.4.3

### ISSUE THREAD

**Issue by visionlineNP** [khaotik/dnc-theano#2]
$ python3
Python 3.4.3 (default, Sep 14 2016, 12:36:27) 
[GCC 4.8.4] on linux

$ python3 -i dnc.py 
Traceback (most recent call last):
  File "dnc.py", line 10, in <module>
    from optimize import AdamSGD
  File "/home/norm/python/dnc/dnc-theano/optimize.py", line 154
    return self.fn_train(self.lr,*v_x_li_,b1,b2,b1s,b2s)
                                                 
SyntaxError: only named arguments may follow *expression

*please note* the syntax error is under the "b1s" variable.

**Comment by khaotik** [comment]
@visionlineNP Made a fix, should work with py34 now.
